export enum StatusColis{
    NON_ENVOYE="NON_ENVOYE",
    ENVOYE   ="EN_RECEPTION",
    EN_NETWORK="EN_NETWORK",
    EXPEDITION="EN_EXPEDITION",
    RECEPTION_HUB="EN_RECEPTION_AU_HUB",
    EN_HUB ="EN_HUB",
    ENCOUR_DELEVRY = "EN_COUR_DELEVRY",
    RECOMANDER="RECOMANDER",
    RAPALLE="RAPALLE",
    ANUULE="ANUULE",
    REFUSE="REFUSE",
    RETOURE_TO_NETWORK="RETOURE_TO_NETWORK",
    RETOURE_EN_NETWORK="RETOURE_EN_NETWORK",
    RETOURE_TO_VENDEUR="RETOURE_TO_VENDEUR",
    RETOURNER="RETOURNER",
    RETOURNER_ATT="RETOURNER_ATT",
    DELEVRY="DELEVRY",
    RECUPIRER="RECUPIRER"


}



